---
# yamllint disable rule:line-length
name: Lazy Action Nodejs
description: |
  Github Action to perform build, test , scan and generate Image for Nodejs

  ## Permissions

  Add the following permissions to the job

  ```yaml
  permissions:
    id-token: write
    contents: write
  ```

  ## Usage

  ```yaml
      - name: Actions Nodejs
        uses: variant-inc/actions-nodejs@v2
        with:
          ecr_repository: 'demo/example'
          nodejs-version: 18
  ```
inputs:
  cloud_region:
    description: Region where the image will be created.
    default: us-east-2
    required: false
  dockerfile_dir_path:
    description: Directory path to the dockerfile
    required: false
    default: .
  ecr_repository:
    description: Ecr repository name
    required: false
  nodejs-version:
    description: >
      The nodejs-version input is optional.
      The default version of Nodejs in PATH varies
      between runners and can be changed unexpectedly
      so we recommend always setting Nodejs version explicitly
      using the nodejs-version input.
    required: false
  npm_package_publish:
    description: Enabled npm Package Publish to AzureDevops.
    required: false
    default: 'false'
  npm_test_script_name:
    description: npm test script name
    required: false
    default: test
runs:
  using: composite
  steps:
    - name: Setup Actions
      uses: variant-inc/actions-setup@v2

    - name: Sonar Setup
      id: sonar-setup
      uses: variant-inc/actions-collection/sonar-setup@v2

    - name: Relocate Test Actions
      shell: bash
      run: |
        mkdir -p ./.github/workflows/actions-nodejs/test
        cp -R ${{ github.action_path }}/test/* ./.github/workflows/actions-nodejs/test/
        mkdir -p ./.github/workflows/actions-nodejs/publish
        cp -R ${{ github.action_path }}/publish/* ./.github/workflows/actions-nodejs/publish/

    - name: Build & Test Nodejs
      uses: ./.github/workflows/actions-nodejs/test
      if: ${{ steps.sonar-setup.outputs.sonar_skip != 'True' }}
      with:
        nodejs-version: ${{ inputs.nodejs-version }}
        npm_test_script_name: ${{ inputs.npm_test_script_name }}
        sonar_wait_flag: ${{ steps.sonar-setup.outputs.wait_flag }}

    - name: Sonar Coverage Check
      id: sonar-coverage-check
      uses: variant-inc/actions-collection/sonar-coverage-check@v2
      if: ${{ steps.sonar-setup.outputs.wait_flag == 'true' }}

    - name: Build and Push Image
      uses: variant-inc/actions-collection/build-push-image@v2
      if: ${{ inputs.ecr_repository != '' }}
      with:
        dockerfile_dir_path: ${{ inputs.dockerfile_dir_path }}
        ecr_repository: ${{ inputs.ecr_repository }}
        aws_region: ${{ inputs.cloud_region }}

    - name: Azure Devops npm Publish
      if: ${{ inputs.npm_package_push == 'true' }}
      shell: bash
      run: ./.github/workflows/actions-nodejs/publish/npm_package_publish.sh

    - name: Create Release Action
      uses: variant-inc/actions-collection/create-release-tag@v2
      if: ${{ inputs.npm_package_push == 'true' && inputs.ecr_repository == '' }}

    - name: Set Language env
      shell: bash
      run: |
        echo "LANGUAGE=nodejs" >> "$GITHUB_ENV"
