---
# yamllint disable rule:line-length
name: Lazy Action Nodejs
description: |
  Github Action to perform build, test , scan and generate Image for Nodejs

  ## Permissions

  Add the following permissions to the job

  ```yaml
  permissions:
    id-token: write
    contents: read
  ```

  ## Usage

  ```yaml
      - name: Actions Nodejs
        uses: variant-inc/actions-nodejs@v2
        with:
          ecr_repository: 'demo/example'
          nodejs-version: 18
  ```
inputs:
  dockerfile_dir_path:
    description: Directory path to the dockerfile
    required: false
    default: .
  npm_test_script_name:
    description: npm test script name
    required: false
    default: test
  ecr_repository:
    description: Ecr repository name
    required: false
  aws_region:
    description: Region where the image will be created.
    default: us-east-2
    required: false
  nodejs-version:
    description: >
      The nodejs-version input is optional.
      The default version of Nodejs in PATH varies
      between runners and can be changed unexpectedly
      so we recommend always setting Nodejs version explicitly
      using the nodejs-version input.
    required: false
runs:
  using: composite
  steps:
    - name: Setup Actions
      uses: variant-inc/actions-setup@v2

    - name: Sonar Setup
      id: sonar-setup
      uses: variant-inc/actions-collection/sonar-setup@v2

    - name: Relocate Test Action
      shell: bash
      run: |
        mkdir -p ./.github/workflows/actions-nodejs/test
        cp -R ${{ github.action_path }}/test/* ./.github/workflows/actions-nodejs/test/

    - name: Build & Test Nodejs
      uses: ./.github/workflows/actions-nodejs/test
      if: ${{ steps.sonar-setup.outputs.sonar_skip != 'True' }}
      with:
        nodejs-version: ${{ inputs.nodejs-version }}
        npm_test_script_name: ${{ inputs.npm_test_script_name }}

    - name: Build and Push Image
      uses: variant-inc/actions-collection/build-push-image@v2
      if: ${{ inputs.ecr_repository != '' }}
      with:
        dockerfile_dir_path: ${{ inputs.dockerfile_dir_path }}
        ecr_repository: ${{ inputs.ecr_repository }}
        aws_region: ${{ inputs.aws_region }}
