---
name: Linter

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - .github/workflows/branch.yaml

jobs:
  lint:
    name: Lint Code Base
    runs-on: [test]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_KUBERNETES_KUBEVAL: false
          VALIDATE_GITHUB_ACTIONS: false
